### ISSUE TITLE
No Calamares

### ISSUE THREAD

**Issue by letkan** [arch-linux-calamares-installer/alci-iso-lts#1]
Downloaded from github, made iso without touching any files, run in Qemu, the desktop appears but no Calamares. Couldn't launch it manually also
Here's the error:
`calamares: symbol lookup error:/usr/lib/libcalamares.so.3.3 undefined symbol: _ZN0FileSystem!!nameForTypeENS_4TypeERK11QstringList`

**Comment by arcolinuxz** [comment]
you have to make a new calamares yourself
